#pragma once

#include "frame.hpp"

namespace vp
{

/**
 * @brief Base interface for inference models.
 *
 * An inference model implements the complete pipeline required to process an
 * input frame and produce task-specific outputs. The framework does not impose
 * any assumptions on the type of outputs generated by the model.
 */
class InferenceModel
{
public:

    /**
     * @brief Destroys the inference model.
     */
    virtual ~InferenceModel() = default;

    /**
     * @brief Executes the model pipeline.
     *
     * Implementations are responsible for executing the complete inference
     * pipeline required by the model and updating their corresponding outputs.
     *
     * @param frame Input frame.
     */
    virtual void Process(const Frame& frame) = 0;
};

} // namespace vp
